
project_id = "irnkilorodqvhizmujtq"

[functions.extract-text]
verify_jwt = false

[functions.analyze-test] 
verify_jwt = false

[functions.analyze-exam-skills]
verify_jwt = false

[functions.generate-practice-test]
verify_jwt = false

[functions.batch-queue-manager]
verify_jwt = false
