
project_id = "irnkilorodqvhizmujtq"

[functions.extract-text]
verify_jwt = false

[functions.analyze-test] 
verify_jwt = false

[functions.analyze-exam-skills]
verify_jwt = false

[functions.generate-practice-test]
verify_jwt = false

[functions.batch-queue-manager]
verify_jwt = false

[functions.get-question-cache]
verify_jwt = false

[functions.set-question-cache]
verify_jwt = false

[functions.get-question-cache-stats]
verify_jwt = false

[functions.cleanup-question-cache]
verify_jwt = false
